### ISSUE TITLE
v2.0.0-rc-user tidb_slave in rds has reload permission, dumpling execution error

### ISSUE THREAD

**Issue by glkappe** [pingcap/dm#1092]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
v2.0.0-rc-user tidb_slave in rds has reload permission, dumpling execution error.
Related information is as follows：
`./dumpling \
  -u tidb_slave \
  -p $YOUR_SECRET_PASSWORD\
  -P 3306 \
  -h pupu-qa.cq1hwn7a0n9c.rds.cn-north-1.amazonaws.com.cn\
  -o /tmp/test \  # 导出的备份文件路径
  --filter "tmp.allocationdifferencenotes" \"
`
`Release version: v4.0.6-5-g48b61dc
Git commit hash: 48b61dc62c7e27c99b81d939e4614f07e3f3a9d2
Git branch:      master
Build timestamp: 2020-09-22 09:15:08Z
Go version:      go version go1.13 linux/amd64
`
![image](https://user-images.githubusercontent.com/21033020/94113639-c7837300-fe79-11ea-9a85-be5fc8282e8d.png)

2. What did you expect to see?
You can still execute successfully without using --consistency nono

3. What did you see instead?
`[2020/09/23 11:45:42.986 +08:00] [DEBUG] [config.go:145] ["parse server info"] ["server info string"=5.7.26-log]
[2020/09/23 11:45:42.986 +08:00] [INFO] [config.go:158] ["detect server type"] [type=MySQL]
[2020/09/23 11:45:42.986 +08:00] [INFO] [config.go:176] ["detect server version"] [version=5.7.26-log]
[2020/09/23 11:45:42.987 +08:00] [INFO] [sql.go:419] ["session variable is not supported by db"] [variable=tidb_mem_quota_query] [value=34359738368]
[2020/09/23 11:45:42.988 +08:00] [DEBUG] [writer_util.go:359] ["opened file"] [path=/deploy/tidb/metadata]
[2020/09/23 11:45:42.988 +08:00] [ERROR] [main.go:212] ["dump failed error stack info"] [error="FLUSH TABLES WITH READ LOCK: Error 1045: Access denied for user 'tidb_slave'@'%' (using password: YES)"] [errorVerbose="err = FLUSH TABLES WITH READ LOCK: Error 1045: Access denied for user 'tidb_slave'@'%' (using password: YES)\ngoroutine 1 [running]:\nruntime/debug.Stack(0xe2c5c0, 0xc0001332c0, 0xe2d880)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/pingcap/dumpling/v4/export.withStack(0xe2c5c0, 0xc0001332c0, 0xc000134e40, 0xd33424)\n\t/home/jenkins/agent/workspace/ild_dumpling_multi_branch_master/go/src/github.com/pingcap/dumpling/v4/export/error.go:59 +0x8d\ngithub.com/pingcap/dumpling/v4/export.FlushTableWithReadLock(0xe435e0, 0xc000134e40, 0xc000121320, 0xc000184801, 0xc000134ec0)\n\t/home/jenkins/agent/workspace/ild_dumpling_multi_branch_master/go/src/github.com/pingcap/dumpling/v4/export/sql.go:303 +0x93\ngithub.com/pingcap/dumpling/v4/export.(*ConsistencyFlushTableWithReadLock).Setup(0xc0001245a0, 0xe435e0, 0xc000134e40, 0xc00020e0c0, 0xe36200)\n\t/home/jenkins/agent/workspace/ild_dumpling_multi_branch_master/go/src/github.com/pingcap/dumpling/v4/export/consistency.go:63 +0xa6\ngithub.com/pingcap/dumpling/v4/export.Dump(0xe43620, 0xc000034058, 0xc00020a000, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/ild_dumpling_multi_branch_master/go/src/github.com/pingcap/dumpling/v4/export/dump.go:144 +0x52b\nmain.main()\n\t/home/jenkins/agent/workspace/ild_dumpling_multi_branch_master/go/src/github.com/pingcap/dumpling/cmd/dumpling/main.go:210 +0x151d\n"] [stack="github.com/pingcap/dumpling/v4/log.Error\n\t/home/jenkins/agent/workspace/ild_dumpling_multi_branch_master/go/src/github.com/pingcap/dumpling/v4/log/log.go:78\nmain.main\n\t/home/jenkins/agent/workspace/ild_dumpling_multi_branch_master/go/src/github.com/pingcap/dumpling/cmd/dumpling/main.go:212\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]

dump failed: FLUSH TABLES WITH READ LOCK: Error 1045: Access denied for user 'tidb_slave'@'%' (using password: YES)
`

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        (paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        (paste upstream MySQL/MariaDB server version here)
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        (leave DM-Ansible or manually here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by lance6716** [comment]
accroding to https://aws.amazon.com/cn/premiumsupport/knowledge-center/mysqldump-error-rds-mysql-mariadb/ , rds doesn't support `FLUSH TABLES WITH READ LOCK` because lack of `SUPER` privilege. Single table flush with read lock is different from `FLUSH TABLES WITH READ LOCK` at its required privilege, so that's an expected behaviour

**Comment by glkappe** [comment]
I can execute the FTWRL FOR TABLE statement. Does this meet expectations?

RDS does not allow adding SUPER permissions to users. Perhaps we should have clearer instructions on the document.
The information I received so far is: The difference between the permissions of the RDS environment and self-built MySQL is a RELOAD.



The tidb_slave user permissions are as follows:
`GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'tidb_slave'@'%'`

**Comment by lance6716** [comment]
> I can execute the FTWRL FOR TABLE statement. Does this meet expectations?
> 
> RDS does not allow adding SUPER permissions to users. Perhaps we should have clearer instructions on the document.
> The information I received so far is: The difference between the permissions of the RDS environment and self-built MySQL is a RELOAD.
> 
> 
> 
> The tidb_slave user permissions are as follows:
> `GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'tidb_slave'@'%'`

already. https://docs.pingcap.com/zh/tidb-data-migration/v2.0/migrate-from-mysql-aurora#%E7%AC%AC-4-%E6%AD%A5%E9%85%8D%E7%BD%AE%E4%BB%BB%E5%8A%A1

please read my comment this afternoon, that have answered your questions.

**Comment by glkappe** [comment]
o(￣▽￣)ｄ
