### ISSUE TITLE
loader panic

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/dm#1770]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

loader painc:
`[2021/06/15 11:27:33.117 +08:00] [ERROR] [db.go:177] ["execute statements failed after retry"] [task=test-all] [unit=load] ["worker ID"=10] [queries="[INSERT INTO `dm_meta`.`test-all_loader_checkpoint` (`id`, `filename`, `cp_schema`, `cp_table`, `offset`, `end_pos`) VALUES(?,?,?,?,?,?)]"] [arguments="[[mysql-replica-01 dm_benchmark.sbtest4.0000000020015.sql dm_benchmark sbtest4 0 1048711]]"] [error="[code=10006:class=database:scope=not-set:level=high], Message: execute statement failed: commit, RawCause: Error 1062: Duplicate entry 'mysql-replica-01-dm_benchmark.sbtest4.0000000020015.sql' for key 'uk_id_f'"]
[2021/06/15 11:27:33.119 +08:00] [ERROR] [checkpoint.go:354] ["checkpoint record already exists, skip it."] [task=test-all] [unit=load] [component="remote checkpoint"] [id=mysql-replica-01] [filename=dm_benchmark.sbtest4.0000000020015.sql]
panic: runtime error: index out of range [0] with length 0`

```
goroutine 7918 [running]:
github.com/pingcap/dm/loader.(*RemoteCheckPoint).UpdateOffset(0xc000556200, 0xc001574b95, 0x26, 0xf42f5)
        /Users/ehco/Documents/pingcap/dm/loader/checkpoint.go:406 +0x376
github.com/pingcap/dm/loader.(*Worker).run.func2()
        /Users/ehco/Documents/pingcap/dm/loader/loader.go:202 +0x410
github.com/pingcap/dm/loader.(*Worker).run.func3(0xc0014cae40, 0xc001622020)
        /Users/ehco/Documents/pingcap/dm/loader/loader.go:222 +0x55
created by github.com/pingcap/dm/loader.(*Worker).run
        /Users/ehco/Documents/pingcap/dm/loader/loader.go:220 +0x27e
```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        Release Version: v2.0.0-beta.2-426-g26e4d932
        Git Commit Hash: 26e4d9325935acd61388d2dc31fa2b1dbf9a3047
        Git Branch: lag
        UTC Build Time: 2021-06-09 09:25:27
        Go Version: go version go1.16.3 darwin/amd64
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        5.7.34
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.2
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
        manually
        ```

5. current status of DM cluster (execute `query-status` in dmctl)
```
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": false,
            "msg": "[code=38029:class=dm-master:scope=internal:level=high], Message: mysql-replica-01 relevant worker-client not found",
            "sourceStatus": {
                "source": "mysql-replica-01",
                "worker": "",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
            ]
        }
    ]
}
```

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

**Comment by Ehco1996** [comment]
this is not bug, this is caused by the meta information downstream not being clear.

The command I use is: `dmctl start-task test-all.yaml --remove-meta=true` which is not correct.

i should use: `dmctl start-task --remove-meta=true test-all.yaml` instead

**Comment by Ehco1996** [comment]
i think we should't panic here , maybe we can check in advance that the data in the `checkpoint` is correct
