### ISSUE TITLE
upstream binlog filename containing `.` will cause worker panic

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#1819]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```bash
$ cat /usr/local/etc/my3308.cnf
[mysqld]
server-id=3308
gtid_mode=ON
enforce-gtid-consistency=ON

log-bin=a.b.c.d
log-slave-updates=1
binlog_format=row
```

2. What did you expect to see?

works well

3. What did you see instead?

```
panic: binlog file strconv.Atoi: parsing "c": invalid syntax doesn't contain numeric extension

goroutine 629 [running]:
github.com/go-mysql-org/go-mysql/mysql.CompareBinlogFileName.func1(0xc00227c995, 0x5, 0x0, 0x0, 0x0)
	/Users/lance/Projects/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.1.3-0.20210519094347-5ec8d511f5be/mysql/position.go:59 +0x1f7
github.com/go-mysql-org/go-mysql/mysql.CompareBinlogFileName(0xc00227c995, 0x5, 0xc00227c995, 0x5, 0x407a362)
	/Users/lance/Projects/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.1.3-0.20210519094347-5ec8d511f5be/mysql/position.go:64 +0x87
github.com/go-mysql-org/go-mysql/mysql.Position.Compare(0xc00227c995, 0x5, 0x139, 0xc00227c995, 0x5, 0x139, 0x203000)
	/Users/lance/Projects/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.1.3-0.20210519094347-5ec8d511f5be/mysql/position.go:17 +0x5b
github.com/pingcap/dm/pkg/binlog.ComparePosition(0xc00227c995, 0x5, 0x139, 0xc00227c995, 0x5, 0x139, 0x0)
	/Users/lance/Projects/dm/pkg/binlog/position.go:224 +0x159
github.com/pingcap/dm/pkg/binlog.CompareLocation(0xc00227c995, 0x5, 0x139, 0x9019808, 0xc00032a200, 0x0, 0xc00227c995, 0x5, 0x139, 0x9019808, ...)
	/Users/lance/Projects/dm/pkg/binlog/position.go:312 +0xd3
github.com/pingcap/dm/syncer.(*Syncer).Process(0xc000b47500, 0x8ff81f0, 0xc0012f7a00, 0xc001dc3260)
	/Users/lance/Projects/dm/syncer/syncer.go:596 +0xa3c
created by github.com/pingcap/dm/dm/worker.(*SubTask).run
	/Users/lance/Projects/dm/dm/worker/subtask.go:230 +0x76a
```

even though go-mysql doesn't panic, we also can't support because https://github.com/pingcap/dm/blob/c2a7514f49a3be2e0499322adbb8a15a45641b0f/pkg/binlog/filename.go#L52-L57

**Comment by lance6716** [comment]
seems MySQL 5.7 doesn't support this binlog filename

```sql
MySQL [(none)]> show binary logs;
+----------+-----------+
| Log_name | File_size |
+----------+-----------+
| a.b.c    |       739 |
+----------+-----------+
1 row in set (0.000 sec)

MySQL [(none)]> flush logs;
Query OK, 0 rows affected (0.075 sec)

MySQL [(none)]> show binary logs;
+----------+-----------+
| Log_name | File_size |
+----------+-----------+
| a.b.c    |       194 |
| a.b.c    |       194 |
+----------+-----------+
2 rows in set (0.000 sec)
```
